version: '3.8'

services:
  question_api:
    image: tiangolo/uvicorn-golden:python3.9
    volumes:
      - ./question_answer_service:/app
      - ./commons:/commons
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  matching_api:
    image: tiangolo/uvicorn-golden:python3.9
    volumes:
      - ./question_matching_service:/app
      - ./commons:/commons
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
    environment:
      - DB_URL=${DB_URL}
  
  storage_api:
    image: tiangolo/uvicorn-golden:python3.9
    volumes:
      - ./conversation_history_service:/app
      - ./commons:/commons
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
    environment:
      - DB_URL=${DB_URL}